language: node_js
node_js:
  - 12
notifications:
  email: false
cache:
  directories:
    - node_modules
install:
  - npm install
jobs:
  include:
    - stage: "Test & Build"
      script: npm run test && npm run build
    - stage: "Build & Deploy Staging"
      script: npm run generate:stage
      deploy:
        provider: firebase
        edge: true
        skip_cleanup: true
        token: $FIREBASE_TOKEN
        project: bt-web-staging
    - stage: "Build & Deploy Production"
      script: npm run generate:prod
      deploy:
        provider: firebase
        edge: true
        skip_cleanup: true
        token: $PROD_FIREBASE_TOKEN
        project: bt-web-19a7b
stages:
  - "Test & Build"
  - name: "Build & Deploy Staging"
    if: (branch = master) AND (type = push)
  - name: "Build & Deploy Production"
    if: (branch = prod) AND (type = push)
